routes/web.php
<?php

use App\Http\Controllers\BrandController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','Frontend\HomeController@index')->name('home');
Route::get('/admin/login','Backend\LoginController@index')->name('admin.login');
Route::post('/admin/login','Backend\LoginController@login')->name('admin.login.post');

Route::get('/page/{slugString}','Frontend\CustomPageController@index')->name('custom.page');
Route::get('/brand/{slugString}','Frontend\BrandController@index')->name('brand.page');


Route::get('/brand/{slugString}/{productModel}','Frontend\Brand\ProductsController@index')->name('brand.product.detail');



Route::prefix('backend')->middleware('backend')->group(function () {

    Route::get('/dashboard','Backend\DashboardController@index')->name('admin.dashboard');

    Route::resource('/brands', \Backend\BrandController::class);
    Route::resource('/categories', \Backend\CategoryController::class);
    Route::resource('/sub-categories', \Backend\SubCategoryController::class);
    Route::resource('/sub-category-types', \Backend\SubCategoryTypeController::class);
    Route::resource('/brandPageSliders', \Backend\BrandPageSliderController::class);
    Route::resource('/product-features', \Backend\ProductFeatureController::class);
    Route::resource('/product-feature-values', \Backend\ProductFeatureValueController::class);
    Route::resource('/products', \Backend\ProductController::class);
    Route::post('/product-image-delete/{imageId}', 'Backend\ProductController@destroyProductImage');


    Route::get('form/product/ajax/sub-categories-via-category/{categoryId}', function($categoryId){
        $category = \App\Models\Category::find($categoryId);
        return $category->subCategories()->orderBy('name', 'asc')->pluck('name', 'id');
    });
    Route::get('form/product/ajax/sub-category-types-via-sub-category/{subCategoryId}', function($subCategoryId){
        $subCategory = \App\Models\SubCategory::find($subCategoryId);
        return $subCategory->subCategoryTypes()->orderBy('name', 'asc')->pluck('name', 'id');
    });


    Route::get('form/product/ajax/feature_values-via-feature/{featureId}', function($featureId){
        $feature = \App\Models\ProductFeature::find($featureId);
        return $feature->productFeatureValues()->orderBy('value', 'asc')->pluck('value', 'value');
    });


    Route::get('brand/{brandId}/profile', function($brandId){
        $brand = \App\Models\Brand::find($brandId);
        return view('backend.brand.profile', compact('brand'));
    })->name('brand.profile');

    Route::resource('/pages', \Backend\PageController::class);
    Route::resource('/news', \Backend\NewsController::class);
    Route::resource('/timelines', \Backend\TimelineController::class);
    Route::resource('/homeSliders', \Backend\HomeSliderController::class);
    Route::resource('/menuBuilders', \Backend\MenuBuilderController::class);
    Route::get('/menuBuilders/copy/{menuBuilder}', 'Backend\MenuBuilderController@copyMenu')->name('menuBuilders.copy');

    Route::get('/menuBuilders/parent/{parentId}', 'Backend\MenuBuilderController@checkParent')->name('menuBuilders.checkparent');

    Route::resource('/abouts', \Backend\AboutController::class);
    Route::get('/admin/logout','Backend\LoginController@logout')->name('admin.logout');

});

app/Http/Controllers/Backend/AboutController.php
<?php

namespace App\Http\Controllers\Backend;

use App\FileUpload\FileUpload;
use App\Http\Controllers\Controller;
use App\Models\About;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class AboutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $abouts = About::latest()->get();
        return view('backend.about.index',compact('abouts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.about.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title' => 'required',
            'image' => 'mimes:jpeg,png,bmp,tiff,jpg,webp |max:4096|required',
        ]);
        $inputs = $request->all();

        if ($request->hasFile('image')) {
            $inputs['image'] = FileUpload::uploadFile($request->file('image'), 'images/about');
        }
        $insert = [
            'sort_number' => $inputs['sort_number'],
            'title' => $inputs['title'],
            'body' => $inputs['body'],
            'image' => $inputs['image'],
            'status' => $request->has('status'),

        ];

        About::insertGetId($insert);
        return redirect()->route('abouts.index')->with('success','About created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\About  $about
     * @return \Illuminate\Http\Response
     */
    public function show(About $about)
    {
        return view('backend.about.show',compact('about'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\About  $about
     * @return \Illuminate\Http\Response
     */
    public function edit(About $about)
    {
        return view('backend.about.edit',compact('about'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\About  $about
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, About $about)
    {
        $this->validate($request,[
            'title' => 'required',
            'image' => 'mimes:jpeg,png,bmp,tiff,jpg,webp |max:4096',
        ]);
        $inputs = $request->all();
        if ($request->hasFile('image')) {
            File::delete($about->image);
            $inputs['image'] = FileUpload::uploadFile($request->file('image'), 'images/about');
        }else{
            $inputs['image'] = $about->image;
        }
        $insert = [
            'sort_number' => $inputs['sort_number'],
            'title' => $inputs['title'],
            'body' => $inputs['body'],
            'image' => $inputs['image'],
            'status' => $request->has('status'),
        ];

        $about->update($insert);
        return redirect()->route('abouts.index')->with('success','About Updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\About  $about
     * @return \Illuminate\Http\Response
     */
    public function destroy(About $about)
    {
        if (!request()->ajax()) {
            return false;
        }
        File::delete($about->image);
        $about->delete();
        session()->flash('success', 'About Us Deleted.');
        return [
            'status' => 'success',
            'return_url' => route('abouts.index')
        ];
    }
}

app/Http/Controllers/Backend/BrandController.php
<?php

namespace App\Http\Controllers\Backend;

use App\FileUpload\FileUpload;
use App\Http\Controllers\Controller;
use App\Models\Brand;
use Illuminate\Http\Request;
use Cviebrock\EloquentSluggable\Services\SlugService;
use Illuminate\Support\Facades\File;

class BrandController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $brands = Brand::latest()->get();
        return view('backend.brand.index',compact('brands'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.brand.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required',
            'code' => 'required',
            'brand_color_code' => 'required',
            'logo' => 'mimes:jpeg,png,bmp,tiff,jpg,webp |max:4096|required',
        ]);
        $inputs = $request->all();
        $inputs['name'] = ucwords($request->name);
        $inputs['status'] = $request->has('status');
        $inputs['slug'] = SlugService::createSlug(Brand::class, 'slug', $request->name);
        if ($request->hasFile('logo')) {
            $inputs['logo'] = FileUpload::uploadFile($request->file('logo'), 'logo/brand');
        }
        Brand::create($inputs);
        return redirect()->route('brands.index')->with('success','Brand created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function show(Brand $brand)
    {
        return view('backend.brand.show',compact('brand'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function edit(Brand $brand)
    {
        return view('backend.brand.edit',compact('brand'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Brand $brand)
    {
        $this->validate($request,[
            'name' => 'required',
            'code' => 'required',
            'brand_color_code' => 'required',
            'logo' => 'mimes:jpeg,png,bmp,tiff,jpg,webp |max:4096',
        ]);
        $inputs = $request->all();
        if ($request->hasFile('logo')) {
            File::delete($brand->logo);
            $inputs['logo'] = FileUpload::uploadFile($request->file('logo'), 'logo/brand');
        }else{
            $inputs['logo'] = $brand->logo;
        }

        $inputs['status'] = $request->has('status');
        $brand->update($inputs);
        return redirect()->route('brands.index')->with('success','Brand Updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function destroy(Brand $brand)
    {
        if (!request()->ajax()) {
            return false;
        }
        File::delete($brand->logo);
        $brand->delete();
        session()->flash('success', 'Brand Deleted.');
        return [
            'status' => 'success',
            'return_url' => route('brands.index')
        ];
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Brand;
use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Cviebrock\EloquentSluggable\Services\SlugService;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $brand = Brand::find($_GET['brand_id']);
        $categories = Category::where('brand_id', $brand->id)->latest()->get();
        return view('backend.categories.index',compact('categories', 'brand'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $brand = Brand::find($_GET['brand_id']);
        return view('backend.categories.create', compact('brand'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required',
            'code' => 'required',
            'brand_id' => 'required|integer',
        ]);
        $brand = Brand::find($_GET['brand_id']);
        $inputs = $request->all();
        $inputs['brand_id'] = $brand->id;
        $inputs['status'] = $request->has('status');
        $inputs['name'] = ucwords($request->name);
        $inputs['slug'] = SlugService::createSlug(Category::class, 'slug', $request->name);
        Category::create($inputs);
        return redirect()->route('categories.index', ['brand_id' => $brand->id])->with('success','Category created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        $brand = Brand::find($_GET['brand_id']);
        return view('backend.categories.show',compact('category', 'brand'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $brand = Brand::find($_GET['brand_id']);
        return view('backend.categories.edit', compact('category', 'brand'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $this->validate($request,[
            'name' => 'required',
            'brand_id' => 'required|integer',
        ]);
        $brand = Brand::find($_GET['brand_id']);
        $inputs = $request->all();
        $inputs['brand_id'] = $brand->id;
        $inputs['status'] = $request->has('status');
        $inputs['name'] = ucwords($request->name);
        $category->update($inputs);
        return redirect()->route('categories.index', ['brand_id' => $brand->id])->with('success','Category Updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        if (!request()->ajax()) {
            return false;
        }
        $brand = Brand::find($_GET['brand_id']);
        $category->delete();
        session()->flash('success', 'Category Deleted.');
        return [
            'status' => 'success',
            'return_url' => route('categories.index', ['brand_id' => $brand->id])
        ];
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index(){
        return view('backend.dashboard.index');
    }
}

app/Http/Controllers/Backend/LoginController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Contracts\Session\Session;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class LoginController extends Controller
{
    public function index(){
        return view('backend.login.index');
    }

    public function login(Request $request){

        $this->validate($request,[
            'email' =>'required',
            'password' =>'required',
        ]);

        $email = $request['email'];
        $password = $request['password'];
        if (
            Auth::attempt(['email' => $email, 'password' => $password])) {
                session()->flash('success', 'Login Successfully');
                return redirect()->route('admin.dashboard');
        }
        session()->flash('error', 'Username and Password does not match');
        return redirect()->back();
    }


    public function logout()
    {
        Auth::logout();
        Session::flush();
        session()->flash('success', 'Logout Successfully');
        return redirect()->route('admin.login');
    }
}

resources/views/backend/layouts/brandMenu.blade.php
<!-- begin #top-menu -->
<div id="top-menu" class="top-menu" style="top: 50px; position: absolute;margin-left: 220px;z-index:0;">
    <!-- begin nav -->
    <ul class="nav">
        <li class="has-sub">
            <a href="javascript:;">
                <i class="fa fa-th-large"></i>
                <span>Product Catalog</span>
                <b class="caret"></b>
            </a>
            <ul class="sub-menu">
                <li><a href="{{route('categories.index', ['brand_id' => $brand->id])}}">Category</a></li>
                <li><a href="{{route('sub-categories.index', ['brand_id' => $brand->id])}}">Sub Category</a></li>
                <li><a href="{{route('sub-category-types.index', ['brand_id' => $brand->id])}}">Sub Category Type</a></li>
                <li><a href="{{route('product-features.index', ['brand_id' => $brand->id])}}">Product Feature</a></li>
                <li><a href="{{route('product-feature-values.index', ['brand_id' => $brand->id])}}">Product Feature Value</a></li>
                <li><a href="{{route('products.index', ['brand_id' => $brand->id])}}">Product</a></li>
            </ul>
        </li>
        <li class="has-sub">
            <a href="javascript:;">
                <i class="fa fa-hdd"></i>
                <span>Sliders</span>
                <b class="caret"></b>
            </a>
            <ul class="sub-menu">
                <li><a href="{{route('brandPageSliders.index', ['type' => 'Brand','brand_id' => $brand->id])}}">Brand</a></li>
                <li><a href="{{route('brandPageSliders.index', ['type' => 'Category','brand_id' => $brand->id])}}">Category</a></li>
                <li><a href="{{route('brandPageSliders.index', ['type' => 'Sub Category','brand_id' => $brand->id])}}">Sub Category</a></li>
                <li><a href="{{route('brandPageSliders.index', ['type' => 'Sub Category Type','brand_id' => $brand->id])}}">Sub Category Type</a></li>
            </ul>
        </li>
        <li>
            <a href="widget.html">
                <i class="fab fa-simplybuilt"></i>
                <span>Widgets <span class="label label-theme">NEW</span></span>
            </a>
        </li>
        <li class="has-sub">
            <a href="javascript:;">
                <i class="fa fa-gem"></i>
                <span>UI Elements <span class="label label-theme">NEW</span></span>
                <b class="caret"></b>
            </a>
            <ul class="sub-menu">
                <li><a href="ui_general.html">General <i class="fa fa-paper-plane text-theme"></i></a></li>
                <li><a href="ui_typography.html">Typography</a></li>
                <li><a href="ui_tabs_accordions.html">Tabs & Accordions</a></li>
                <li><a href="ui_unlimited_tabs.html">Unlimited Nav Tabs</a></li>
                <li><a href="ui_modal_notification.html">Modal & Notification <i class="fa fa-paper-plane text-theme"></i></a></li>
                <li><a href="ui_widget_boxes.html">Widget Boxes</a></li>
                <li><a href="ui_media_object.html">Media Object</a></li>
                <li><a href="ui_buttons.html">Buttons <i class="fa fa-paper-plane text-theme"></i></a></li>
                <li><a href="ui_icons.html">Icons</a></li>
                <li><a href="ui_simple_line_icons.html">Simple Line Icons</a></li>
                <li><a href="ui_ionicons.html">Ionicons</a></li>
                <li><a href="ui_tree.html">Tree View</a></li>
                <li><a href="ui_language_bar_icon.html">Language Bar & Icon</a></li>
                <li><a href="ui_social_buttons.html">Social Buttons</a></li>
                <li><a href="ui_tour.html">Intro JS</a></li>
            </ul>
        </li>
    </ul>
    <!-- end nav -->
</div>
<!-- end #top-menu -->

resources/views/backend/layouts/message.blade.php
@if($errors->any())
<script>
// $(window).on('load', function() {
    setTimeout(function() {
        $.gritter.add({
            title: 'Form Required',
            text: 'Validation Error',
            sticky: true,
            time: '',
            class_name: 'my-sticky-class'
        });
    }, 1000);
// });


</script>
<style>
    body #gritter-notice-wrapper .gritter-item-wrapper{
        background: #ff5b57;
        color:white;
    }
    body #gritter-notice-wrapper .gritter-item-wrapper .gritter-item p{
        color:white;
    }
    body #gritter-notice-wrapper .gritter-item-wrapper .gritter-item .gritter-close{
        color:white;
    }
</style>
@endif

@if(session()->has('success'))
<script>
    let message = "{{session()->get('success')}}";
    setTimeout(function() {
        $.gritter.add({
            title: 'Success',
            text: message,
            sticky: true,
            time: '',
            class_name: 'my-sticky-class'
        });
    }, 1000);


</script>
<style>
    body #gritter-notice-wrapper .gritter-item-wrapper{
        background: #00770a;
        color:white;
    }
    body #gritter-notice-wrapper .gritter-item-wrapper .gritter-item p{
        color:white;
    }
    body #gritter-notice-wrapper .gritter-item-wrapper .gritter-item .gritter-close{
        color:white;
    }
</style>
@endif
@if(session()->has('error'))
<script>
    let message = "{{session()->get('error')}}";
    setTimeout(function() {
        $.gritter.add({
            title: 'Success',
            text: message,
            sticky: true,
            time: '',
            class_name: 'my-sticky-class'
        });
    }, 1000);


</script>
<style>
    body #gritter-notice-wrapper .gritter-item-wrapper{
        background: #b92727;
        color:white;
    }
    body #gritter-notice-wrapper .gritter-item-wrapper .gritter-item p{
        color:white;
    }
    body #gritter-notice-wrapper .gritter-item-wrapper .gritter-item .gritter-close{
        color:white;
    }
</style>
@endif