routes/web.php
<?php

use App\Http\Controllers\BrandController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','Frontend\HomeController@index')->name('home');
Route::get('/admin/login','Backend\LoginController@index')->name('admin.login');
Route::post('/admin/login','Backend\LoginController@login')->name('admin.login.post');

Route::get('/page/{slugString}','Frontend\CustomPageController@index')->name('custom.page');
Route::get('/brand/{slugString}','Frontend\BrandController@index')->name('brand.page');


Route::get('/brand/{slugString}/{productModel}','Frontend\Brand\ProductsController@index')->name('brand.product.detail');



Route::prefix('backend')->middleware('backend')->group(function () {

    Route::get('/dashboard','Backend\DashboardController@index')->name('admin.dashboard');

    Route::resource('/brands', \Backend\BrandController::class);
    Route::resource('/categories', \Backend\CategoryController::class);
    Route::resource('/sub-categories', \Backend\SubCategoryController::class);
    Route::resource('/sub-category-types', \Backend\SubCategoryTypeController::class);
    Route::resource('/brandPageSliders', \Backend\BrandPageSliderController::class);
    Route::resource('/product-features', \Backend\ProductFeatureController::class);
    Route::resource('/product-feature-values', \Backend\ProductFeatureValueController::class);
    Route::resource('/products', \Backend\ProductController::class);
    Route::post('/product-image-delete/{imageId}', 'Backend\ProductController@destroyProductImage');


    Route::get('form/product/ajax/sub-categories-via-category/{categoryId}', function($categoryId){
        $category = \App\Models\Category::find($categoryId);
        return $category->subCategories()->orderBy('name', 'asc')->pluck('name', 'id');
    });
    Route::get('form/product/ajax/sub-category-types-via-sub-category/{subCategoryId}', function($subCategoryId){
        $subCategory = \App\Models\SubCategory::find($subCategoryId);
        return $subCategory->subCategoryTypes()->orderBy('name', 'asc')->pluck('name', 'id');
    });


    Route::get('form/product/ajax/feature_values-via-feature/{featureId}', function($featureId){
        $feature = \App\Models\ProductFeature::find($featureId);
        return $feature->productFeatureValues()->orderBy('value', 'asc')->pluck('value', 'value');
    });


    Route::get('brand/{brandId}/profile', function($brandId){
        $brand = \App\Models\Brand::find($brandId);
        return view('backend.brand.profile', compact('brand'));
    })->name('brand.profile');

    Route::resource('/pages', \Backend\PageController::class);
    Route::resource('/news', \Backend\NewsController::class);
    Route::resource('/timelines', \Backend\TimelineController::class);
    Route::resource('/homeSliders', \Backend\HomeSliderController::class);
    Route::resource('/menuBuilders', \Backend\MenuBuilderController::class);
    Route::get('/menuBuilders/copy/{menuBuilder}', 'Backend\MenuBuilderController@copyMenu')->name('menuBuilders.copy');

    Route::get('/menuBuilders/parent/{parentId}', 'Backend\MenuBuilderController@checkParent')->name('menuBuilders.checkparent');

    Route::resource('/abouts', \Backend\AboutController::class);
    Route::get('/admin/logout','Backend\LoginController@logout')->name('admin.logout');

});

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use Cviebrock\EloquentSluggable\Sluggable;
use Cviebrock\EloquentSluggable\SluggableScopeHelpers;

class News extends Model
{
    use HasFactory;

    use Sluggable;
    use SluggableScopeHelpers;
    protected $fillable = [
        'brand_id',
        'title',
        'date',
        'image',
        'body',
        'meta_title',
        'meta_description',
        'meta_keywords',
        'status',
        'slug',
    ];

    public function sluggable() :array
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public function scopeActive($query)
    {
        return $query->where('status', 1);
    }
}

app/Http/Controllers/Backend/AboutController.php
<?php

namespace App\Http\Controllers\Backend;

use App\FileUpload\FileUpload;
use App\Http\Controllers\Controller;
use App\Models\About;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class AboutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $abouts = About::latest()->get();
        return view('backend.about.index',compact('abouts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.about.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title' => 'required',
            'image' => 'mimes:jpeg,png,bmp,tiff,jpg,webp |max:4096|required',
        ]);
        $inputs = $request->all();

        if ($request->hasFile('image')) {
            $inputs['image'] = FileUpload::uploadFile($request->file('image'), 'images/about');
        }
        $insert = [
            'sort_number' => $inputs['sort_number'],
            'title' => $inputs['title'],
            'body' => $inputs['body'],
            'image' => $inputs['image'],
            'status' => $request->has('status'),

        ];

        About::insertGetId($insert);
        return redirect()->route('abouts.index')->with('success','About created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\About  $about
     * @return \Illuminate\Http\Response
     */
    public function show(About $about)
    {
        return view('backend.about.show',compact('about'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\About  $about
     * @return \Illuminate\Http\Response
     */
    public function edit(About $about)
    {
        return view('backend.about.edit',compact('about'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\About  $about
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, About $about)
    {
        $this->validate($request,[
            'title' => 'required',
            'image' => 'mimes:jpeg,png,bmp,tiff,jpg,webp |max:4096',
        ]);
        $inputs = $request->all();
        if ($request->hasFile('image')) {
            File::delete($about->image);
            $inputs['image'] = FileUpload::uploadFile($request->file('image'), 'images/about');
        }else{
            $inputs['image'] = $about->image;
        }
        $insert = [
            'sort_number' => $inputs['sort_number'],
            'title' => $inputs['title'],
            'body' => $inputs['body'],
            'image' => $inputs['image'],
            'status' => $request->has('status'),
        ];

        $about->update($insert);
        return redirect()->route('abouts.index')->with('success','About Updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\About  $about
     * @return \Illuminate\Http\Response
     */
    public function destroy(About $about)
    {
        if (!request()->ajax()) {
            return false;
        }
        File::delete($about->image);
        $about->delete();
        session()->flash('success', 'About Us Deleted.');
        return [
            'status' => 'success',
            'return_url' => route('abouts.index')
        ];
    }
}

app/Http/Controllers/Backend/BrandController.php
<?php

namespace App\Http\Controllers\Backend;

use App\FileUpload\FileUpload;
use App\Http\Controllers\Controller;
use App\Models\Brand;
use Illuminate\Http\Request;
use Cviebrock\EloquentSluggable\Services\SlugService;
use Illuminate\Support\Facades\File;

class BrandController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $brands = Brand::latest()->get();
        return view('backend.brand.index',compact('brands'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.brand.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required',
            'code' => 'required',
            'brand_color_code' => 'required',
            'logo' => 'mimes:jpeg,png,bmp,tiff,jpg,webp |max:4096|required',
        ]);
        $inputs = $request->all();
        $inputs['name'] = ucwords($request->name);
        $inputs['status'] = $request->has('status');
        $inputs['slug'] = SlugService::createSlug(Brand::class, 'slug', $request->name);
        if ($request->hasFile('logo')) {
            $inputs['logo'] = FileUpload::uploadFile($request->file('logo'), 'logo/brand');
        }
        Brand::create($inputs);
        return redirect()->route('brands.index')->with('success','Brand created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function show(Brand $brand)
    {
        return view('backend.brand.show',compact('brand'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function edit(Brand $brand)
    {
        return view('backend.brand.edit',compact('brand'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Brand $brand)
    {
        $this->validate($request,[
            'name' => 'required',
            'code' => 'required',
            'brand_color_code' => 'required',
            'logo' => 'mimes:jpeg,png,bmp,tiff,jpg,webp |max:4096',
        ]);
        $inputs = $request->all();
        if ($request->hasFile('logo')) {
            File::delete($brand->logo);
            $inputs['logo'] = FileUpload::uploadFile($request->file('logo'), 'logo/brand');
        }else{
            $inputs['logo'] = $brand->logo;
        }

        $inputs['status'] = $request->has('status');
        $brand->update($inputs);
        return redirect()->route('brands.index')->with('success','Brand Updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function destroy(Brand $brand)
    {
        if (!request()->ajax()) {
            return false;
        }
        File::delete($brand->logo);
        $brand->delete();
        session()->flash('success', 'Brand Deleted.');
        return [
            'status' => 'success',
            'return_url' => route('brands.index')
        ];
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Brand;
use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Cviebrock\EloquentSluggable\Services\SlugService;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $brand = Brand::find($_GET['brand_id']);
        $categories = Category::where('brand_id', $brand->id)->latest()->get();
        return view('backend.categories.index',compact('categories', 'brand'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $brand = Brand::find($_GET['brand_id']);
        return view('backend.categories.create', compact('brand'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required',
            'code' => 'required',
            'brand_id' => 'required|integer',
        ]);
        $brand = Brand::find($_GET['brand_id']);
        $inputs = $request->all();
        $inputs['brand_id'] = $brand->id;
        $inputs['status'] = $request->has('status');
        $inputs['name'] = ucwords($request->name);
        $inputs['slug'] = SlugService::createSlug(Category::class, 'slug', $request->name);
        Category::create($inputs);
        return redirect()->route('categories.index', ['brand_id' => $brand->id])->with('success','Category created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        $brand = Brand::find($_GET['brand_id']);
        return view('backend.categories.show',compact('category', 'brand'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $brand = Brand::find($_GET['brand_id']);
        return view('backend.categories.edit', compact('category', 'brand'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $this->validate($request,[
            'name' => 'required',
            'brand_id' => 'required|integer',
        ]);
        $brand = Brand::find($_GET['brand_id']);
        $inputs = $request->all();
        $inputs['brand_id'] = $brand->id;
        $inputs['status'] = $request->has('status');
        $inputs['name'] = ucwords($request->name);
        $category->update($inputs);
        return redirect()->route('categories.index', ['brand_id' => $brand->id])->with('success','Category Updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        if (!request()->ajax()) {
            return false;
        }
        $brand = Brand::find($_GET['brand_id']);
        $category->delete();
        session()->flash('success', 'Category Deleted.');
        return [
            'status' => 'success',
            'return_url' => route('categories.index', ['brand_id' => $brand->id])
        ];
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index(){
        return view('backend.dashboard.index');
    }
}

app/Http/Controllers/Backend/LoginController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Contracts\Session\Session;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class LoginController extends Controller
{
    public function index(){
        return view('backend.login.index');
    }

    public function login(Request $request){

        $this->validate($request,[
            'email' =>'required',
            'password' =>'required',
        ]);

        $email = $request['email'];
        $password = $request['password'];
        if (
            Auth::attempt(['email' => $email, 'password' => $password])) {
                session()->flash('success', 'Login Successfully');
                return redirect()->route('admin.dashboard');
        }
        session()->flash('error', 'Username and Password does not match');
        return redirect()->back();
    }


    public function logout()
    {
        Auth::logout();
        Session::flush();
        session()->flash('success', 'Logout Successfully');
        return redirect()->route('admin.login');
    }
}

resources/views/backend/news/create.blade.php
@extends('backend.layouts.master')

@section('content')


<div id="content" class="content">
    <!-- begin breadcrumb -->
    <ol class="breadcrumb float-xl-right">
        <li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
        <li class="breadcrumb-item"><a href="javascript:;">News</a></li>
        <li class="breadcrumb-item active">All</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- begin page-header -->
    <h1 class="page-header">Create News <a class="btn btn-sm btn-success" href="{{route('news.index')}}"><i class="fa fa-arrow-left"></i> Back</a><small></small></h1>
    <!-- end page-header -->
    <!-- begin panel -->
    {{Form::open(['method' => 'POST','route' => 'news.store','data-parsley-validate'=>'true','files' => true])}}

    <div class="row">
        <div class="col-lg-7">
            <div class="panel panel-inverse">

                <!-- begin panel-heading -->
                <div class="panel-heading">
                    <h4 class="panel-title">Form</h4>
                    <div class="panel-heading-btn">
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    </div>
                </div>
                <!-- end panel-heading -->
            <!-- begin panel-body -->
            <div class="panel-body">
                    @include('backend.news.form')


            </div>
            <!-- end panel-body -->
        </div>
        </div>
        <div class="col-lg-5">
            <div class="panel panel-inverse">
                <!-- begin panel-heading -->
                <div class="panel-heading">
                    <h4 class="panel-title">Meta Tag Form</h4>
                    <div class="panel-heading-btn">
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    </div>
                </div>
                <!-- end panel-heading -->
            <!-- begin panel-body -->
            <div class="panel-body">
                    @include('backend.layouts.metaTag.form')


            </div>
            <!-- end panel-body -->
        </div>

        </div>

            <div class="col-md-8 col-sm-8">
                <button type="submit" class="btn btn-primary"><i class="fa fa-check-circle"></i> Create</button>
            </div>
    </div>

    {{Form::close()}}
    <!-- end panel -->
</div>


@endsection

resources/views/backend/news/edit.blade.php
@extends('backend.layouts.master')

@section('content')


<div id="content" class="content">
    <!-- begin breadcrumb -->
    <ol class="breadcrumb float-xl-right">
        <li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
        <li class="breadcrumb-item"><a href="javascript:;">News</a></li>
        <li class="breadcrumb-item active">Edit</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- begin page-header -->
    <h1 class="page-header">Edit News <a class="btn btn-sm btn-success" href="{{route('news.index')}}"><i class="fa fa-arrow-left"></i> Back</a><small></small></h1>
    <!-- end page-header -->
    <!-- begin panel -->
    {{Form::model($news,['method' => 'PATCH','route' => ['news.update',$news->id],'data-parsley-validate'=>'true','files' => true])}}

    <div class="row">
        <div class="col-lg-7">
            <div class="panel panel-inverse">

                <!-- begin panel-heading -->
                <div class="panel-heading">
                    <h4 class="panel-title">Form</h4>
                    <div class="panel-heading-btn">
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    </div>
                </div>
                <!-- end panel-heading -->
            <!-- begin panel-body -->
            <div class="panel-body">
                    @include('backend.news.form')


            </div>
            <!-- end panel-body -->
        </div>
        </div>
        <div class="col-lg-5">
            <div class="panel panel-inverse">
                <!-- begin panel-heading -->
                <div class="panel-heading">
                    <h4 class="panel-title">Meta Tag Form</h4>
                    <div class="panel-heading-btn">
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    </div>
                </div>
                <!-- end panel-heading -->
            <!-- begin panel-body -->
            <div class="panel-body">
                    @include('backend.layouts.metaTag.form')


            </div>
            <!-- end panel-body -->
        </div>

        </div>

        <div class="col-md-8 col-sm-8">
                <button type="submit" class="btn btn-primary"><i class="fa fa-check-circle"></i> Update</button>
        </div>
    </div>

    {{Form::close()}}
    <!-- end panel -->
</div>


@endsection

resources/views/backend/news/index.blade.php
@extends('backend.layouts.master')

@section('content')


<div id="content" class="content">
    <!-- begin breadcrumb -->
    <ol class="breadcrumb float-xl-right">
        <li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
        <li class="breadcrumb-item"><a href="javascript:;">News</a></li>
        <li class="breadcrumb-item active">All</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- begin page-header -->
    <h1 class="page-header">News <a class="btn btn-sm btn-success" href="{{route('news.create')}}"><i class="fa fa-plus"></i> Add News</a><small></small></h1>
    <!-- end page-header -->
    <!-- begin panel -->
    <div class="panel panel-inverse">
        <!-- begin panel-heading -->
        <div class="panel-heading">
            <h4 class="panel-title">Table</h4>
            <div class="panel-heading-btn">
                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>

            </div>
        </div>
        <!-- end panel-heading -->
        <!-- begin panel-body -->
        <div class="panel-body">
            <table id="data-table-default" class="table table-striped table-bordered table-td-valign-middle">
                <thead>
                    <tr>
                        <th width="1%"></th>
                        <th class="text-nowrap">Title</th>
                        <th class="text-nowrap">Slug</th>
                        <th class="text-nowrap">Status</th>
                        <th class="text-nowrap">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($news as $new)
                    <tr class="odd gradeX">
                        <td width="1%" class="f-w-600 text-inverse">{{$loop->iteration}}</td>
                        <td><a href="{{route('custom.page',$new->slug)}}" target="_blank">{{$new->title}}</a>  * Click here to go website</td>
                        <td>news/{{$new->slug}}</td>
                        <td>{!!($new->status == 1) ? '<span class="label label-green">Active</span>' : '<span class="label label-danger">In-active</span>'!!} </td>
                        <td class="with-btn-group" nowrap="">
                            <div class="btn-group">
                                <a href="{{route('news.show',$new->id)}}" class="btn btn-info btn-sm width-90"><i class="fa fa-eye"></i> View</a>
                                <a href="#" class="btn btn-info btn-sm dropdown-toggle width-30 no-caret" data-toggle="dropdown" aria-expanded="false">
                                <span class="caret"></span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" style="">
                                    <a href="{{route('news.edit',$new->id)}}" class="dropdown-item"><i class="fa fa-edit"></i> Edit</a>
                                    <form action="{{ route('news.destroy', [$new->id]) }}"
                                        method="DELETE" class="delete-data-ajax">
                                        {!! csrf_field() !!}
                                        <button type="submit" class="dropdown-item" title="Delete"><i class="fa fa-trash"></i> Delete</button>
                                        </button>
                                    </form>

                                </div>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <!-- end panel-body -->
    </div>
    <!-- end panel -->
</div>


@endsection

resources/views/backend/news/show.blade.php
@extends('backend.layouts.master')

@section('content')


<div id="content" class="content">
    <!-- begin breadcrumb -->
    <ol class="breadcrumb float-xl-right">
        <li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
        <li class="breadcrumb-item"><a href="javascript:;">News</a></li>
        <li class="breadcrumb-item active">All</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- begin page-header -->
    <h1 class="page-header">Show News <a class="btn btn-sm btn-success" href="{{route('news.index')}}"><i class="fa fa-arrow-left"></i> Back</a><small></small></h1>
    <!-- end page-header -->
    <!-- begin panel -->

    <div class="row">
        <div class="col-lg-7">
            <div class="panel panel-inverse">

                <!-- begin panel-heading -->
                <div class="panel-heading">
                    <h4 class="panel-title">Form</h4>
                    <div class="panel-heading-btn">
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    </div>
                </div>
                <!-- end panel-heading -->
            <!-- begin panel-body -->
            <div class="panel-body">
                <div class="form-group row m-b-15">
                    <label class="col-form-label col-md-3">Title</label>
                    <div class="col-md-9">
                        {{$news->title}}
                    </div>
                </div>
                <div class="form-group row m-b-15">
                    <label class="col-form-label col-md-3">Date</label>
                    <div class="col-md-9">
                        {{$news->date}}
                    </div>
                </div>
                <div class="form-group row m-b-15">
                    <label class="col-form-label col-md-3">Image</label>
                    <div class="col-md-9">
                        <img src="{{url($news->image)}}" width="200"/>
                    </div>
                </div>
                @if(isset($news))
                <div class="form-group row m-b-15">
                    <label class="col-form-label col-md-3">Slug</label>
                    <div class="col-md-9">
                        {{$news->slug}}
                    </div>
                </div>
                @endif
                <div class="form-group row m-b-15">
                    <label class="col-form-label col-md-3">Body</label>
                    <div class="col-md-9">
                        {!!$news->body!!}
                    </div>
                </div>
                <div class="form-group row m-b-10">
                    <label class="col-md-3 col-form-label">Status</label>
                    {!!($news->status == 1) ? '<span class="label label-green">Active</span>' : '<span class="label label-danger">In-active</span>'!!}
                </div>


            </div>
            <!-- end panel-body -->
        </div>
        </div>
        <div class="col-lg-5">
            <div class="panel panel-inverse">
                <!-- begin panel-heading -->
                <div class="panel-heading">
                    <h4 class="panel-title">Meta Tag Form</h4>
                    <div class="panel-heading-btn">
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    </div>
                </div>
                <!-- end panel-heading -->
            <!-- begin panel-body -->
            <div class="panel-body">
                    @include('backend.layouts.metaTag.show',['data' => $news])


            </div>
            <!-- end panel-body -->
        </div>

        </div>

            <div class="col-md-8 col-sm-8">
                <a class="btn btn-sm btn-success" href="{{route('news.index')}}"><i class="fa fa-arrow-left"></i> Back</a>
         </div>
    </div>


    <!-- end panel -->
</div>


@endsection